# Generated by Django 6.0.4 on 2026-04-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cake categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_ca_slug_eb057a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='cakes/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allows_custom_message', models.BooleanField(default=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0, help_text='Display price (From KES)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='products.cakecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CakeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('1kg', '1 KG'), ('1.5kg', '1.5 KG'), ('2kg', '2 KG'), ('3kg', '3 KG'), ('tiered', 'Tiered (Custom)'), ('box_of_6', 'Box of 6'), ('box_of_12', 'Box of 12')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.cake')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.caketype')),
            ],
            options={
                'ordering': ['cake', 'size'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.cake')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='cake',
            index=models.Index(fields=['slug'], name='products_ca_slug_2e2825_idx'),
        ),
        migrations.AddIndex(
            model_name='cake',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_ca_is_acti_a6b25f_idx'),
        ),
        migrations.AddIndex(
            model_name='cake',
            index=models.Index(fields=['category', 'is_active'], name='products_ca_categor_f54c92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cakevariant',
            unique_together={('cake', 'type', 'size')},
        ),
    ]
