# Generated by Django 6.0.4 on 2026-04-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='brief',
            field=models.CharField(blank=True, help_text='Short one-liner for product cards', max_length=120),
        ),
        migrations.AlterField(
            model_name='cakevariant',
            name='size',
            field=models.CharField(choices=[('0.5kg', '0.5 KG'), ('1kg', '1 KG'), ('1.5kg', '1.5 KG'), ('2kg', '2 KG'), ('2.5kg', '2.5 KG'), ('3kg', '3 KG'), ('3.5kg', '3.5 KG'), ('4kg', '4 KG'), ('4.5kg', '4.5 KG'), ('5kg', '5 KG')], help_text='Weight of the cake', max_length=20),
        ),
    ]
