# Generated by Django 6.0.4 on 2026-04-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
